apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksscc-75e9"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksscc-75e9"
  template:
    metadata:
      labels:
        app: "aksscc-75e9"
    spec:
      containers:
        - name: "aksscc-75e9"
          image: "acrmicroservices.azurecr.io/aksscc"
          ports:
          - containerPort: 80